# See src/lib/dea/config.rb for optional config values.

# Base directory for dea, application directories, dea temp files, etc. are all relative to this.
base_dir: /tmp/dea_ng

ssl:
  port: 8443
  key_file: spec/fixtures/certs/server.key
  cert_file: spec/fixtures/certs/server.crt

logging:
  level: debug

loggregator:
  router: 127.0.0.1:3456

resources:
  memory_mb: 2048
  memory_overcommit_factor: 2
  disk_mb: 2048
  disk_overcommit_factor: 2

nats_servers:
  - nats://127.0.0.1:4222/

pid_filename: /tmp/dea_ng.pid

warden_socket: /tmp/warden.sock

evacuation_bail_out_time_in_seconds: 900

default_health_check_timeout: 60 # 1 minute

index: 0
domain: "domain.example.com"

staging:
  enabled: true
  environment:
    PATH: /usr/local/ruby/bin
    BUILDPACK_CACHE: /var/vcap/packages/buildpack_cache
  memory_limit_mb: 1024
  disk_limit_mb: 2048
  disk_inode_limit: 200000
  cpu_limit_shares: 512
  max_staging_duration: 900 # 15 minutes

instance:
  disk_inode_limit: 200000
  memory_to_cpu_share_ratio: 8
  max_cpu_share_limit: 256
  min_cpu_share_limit: 1
  nproc_limit: 1024

dea_ruby: /usr/bin/ruby

# For Go-based directory server
directory_server:
  protocol: 'http'
  v2_port: 80
  file_api_port: 1234
  streaming_timeout: 10
  logging:
    level: info

stacks:
  - name: cflinuxfs2
    package_path: /tmp/warden/rootfs
# Hook scripts for droplet start/stop
# hooks:
#   before_start: path/to/script
#   after_start: path/to/script
#   before_stop: path/to/script
#   after_stop: path/to/script

placement_properties:
  zone: "CRAZY_TOWN"

cc_url: https://user:password@cloud_controller_ng.service.cf.internal

hm9000:
  listener_uri: https://hm9000.service.cf.internal:5335
  key_file: spec/fixtures/certs/hm9000_client.key
  cert_file: spec/fixtures/certs/hm9000_client.crt
  ca_file: spec/fixtures/certs/hm9000_ca.crt
